### PR TITLE
Listing only INSTALLED packages in `porter list`

### PR DESCRIPTION
**Pull request by harjyotbagga**
Listing only INSTALLED packages in `porter list`

# What does this change
_This change adds a new subcommand `--all-states` to the list subcommand in porter. As per this change, porter would only show installed packages by default. Adding this new subcommand would include all states._

image

# What issue does it fix
Closes [#2773 ](https://github.com/getporter/porter/issues/2773)

# Notes for the reviewer
_I have added the documentation for the sub-command. I have also modified some test cases (adding `all-states` parameter to display all installations) to print and pass all Unit Test cases. If we feel that we should add/modify the test cases, kindly do let me know._

# Checklist
- [x] Did you write tests?
- [x] Did you write documentation?
- [ ] Did you change porter.yaml or a storage document record? Update the corresponding schema file.
- [x] If this is your first pull request, please add your name to the bottom of our [Contributors][contributors] list. Thank you for making Porter better! 🙇‍♀️

# Reviewer Checklist
* Comment with /azp run test-porter-release if a magefile or build script was modified
* Comment with /azp run porter-integration if it's a non-trivial PR

[contributors]: https://getporter.org/src/CONTRIBUTORS.md

### CODE REVIEW

**Comment by bdegeeter** [comment]
Hello @harjyotbagga! First I just wanted to say thanks for the contribution.  It's great to see someone new engage in the project.

Here's a couple of thoughts I have about the change.   The `--all-namespaces` flag is taken from `kubectl`.  I wonder if we want to adopt a pattern similar to kubectl for additional output filtering.  For example, `kubectl get pods --all-namespaces --field-selector=status.phase!=Running` the `--field-selector` while more work to implement offers more flexibility.  (maybe we just capture this as a future enhancement?)

A page could also be taken from `docker` and just support `-a` and `--all` to show any uninstalled or future states that are related to an installation that no longer exists.  What else should we consider for filtering while at the same time avoiding a new flag for each case?

**Comment by schristoff** [comment]
> For example, `kubectl get pods --all-namespaces --field-selector=status.phase!=Running` the `--field-selector` while more work to implement offers more flexibility.

Ah, dang, I didn't even think of doing something like this. I think this would be ideal. Currently we have separate flags for label, name, namespace. If we keep going down this way we will have a ton of flags - but if we implement `--field-selector` then we can delete those other flags. It looks like `-label` starts to implement this a bit.

@harjyotbagga  - if you're up for changing implementation, then perhaps taking a look at [kubectl's implementation of fieldselector](https://github.com/kubernetes/kubectl/blob/a5b0052b8993ed982e8df8c97de7abc4263b3967/pkg/cmd/top/top_pod.go#L180) and using it "as inspiration" would be a good start. Let me know what you think.

**Comment by harjyotbagga** [comment]
Sure @schristoff I would be up for the challenge. It would take me some time to understand how kubectl implemented the field selector (and some advisory help too). But would definitely like to give it a try.

**Comment by schristoff** [comment]
Hey @harjyotbagga  - just wanted to checkin if there's any assistance I can provide to get this PR merged - or if it is okay if someone else does that?

Let us know! We're happy to help!

**Comment by harjyotbagga** [comment]
Hey @schristoff I tried working on this feature. But faced some issues. Someone else can work on this feature. 
I can bring in the changes I was thinking of in a new PR.

**Pull request closed without merging**
