### PR TITLE
go.mod: Replace `carolynvs/magex` with `uwu-tools/magex` v0.10.0

### PR DESCRIPTION
**Pull request by justaugustus**
# What does this change

- go.mod: Replace `carolynvs/magex` with `uwu-tools/magex` v0.10.0

# What issue does it fix

Original repo will no longer receive updates.
While the package does not require frequent updates, I'd like to ensure that dependents have an import that will receive periodic & security updates.

# Notes for the reviewer

This change was discussed with @schristoff, who is now [also a co-maintainer](https://github.com/uwu-tools/.github/pull/52) of the project.

`uwu-tools/magex` has existing CNCF dependents, including Kubernetes Release Engineering and Project Stacker: https://github.com/uwu-tools/magex/network/dependents

- Fork notice: https://github.com/carolynvs/magex/issues/30
- Attribution: https://github.com/uwu-tools/magex#attribution
- Initial commit: https://github.com/uwu-tools/magex/pull/1
- `v0.10.0` tag (which mirrors [`carolynvs/magex@v0.9.0`](https://github.com/carolynvs/magex/releases/tag/v0.9.0)): https://github.com/uwu-tools/magex/releases/tag/v0.10.0

# Checklist

- [x] (N/A) Did you write tests?
- [x] (N/A) Did you write documentation?
- [x] (N/A) Did you change porter.yaml or a storage document record? Update the corresponding schema file.
- [x] If this is your first pull request, please add your name to the bottom of our [Contributors][contributors] list. Thank you for making Porter better! 🙇‍♀️

[contributors]: https://porter.sh/src/CONTRIBUTORS.md

### CODE REVIEW

**Comment by justaugustus** [comment]
I noticed `get.porter.sh/magefiles` would also need this change, so I've opened a PR here: https://github.com/getporter/magefiles/pull/45

**Comment by troy0820** [comment]
Thanks @justaugustus for doing this. Looking over the PR now.

**Comment by troy0820** [comment]
This looks good to me.  Not sure how you want to do this @schristoff but we can merge this and then the other or the other promote to  `v0.10.0` and then import that to get rid of the indirect dep.

**Comment by justaugustus** [comment]
> ...but we can merge this and then the other or the other promote to v0.10.0 and then import that to get rid of the indirect dep

@troy0820 — Minor aside that getporter/magefiles does not have Dependabot configured (unlike this repo; unsure if that's intentional), so any future updates on the upstream will require manual intervention (which could cause the `magex` versions to diverge).

**Comment by justaugustus** [comment]
Happy to help, Troy!

**Pull request merged**
