### PR TITLE
fix navigation on mobile

### PR DESCRIPTION
**Pull request by Arhell**
# What does this change
_Give a summary of the change, and how it affects end-users. It's okay to copy/paste your commit messages._

_For example if it introduces a new command or modifies a commands output, give an example of you running the command and showing real output here._

# What issue does it fix
Closes https://github.com/getporter/porter/issues/2558

_If there is not an existing issue, please make sure we have context on why this change is needed. See our Contributing Guide for [examples of when an existing issue isn't necessary][1]._

[1]: https://getporter.org/src/CONTRIBUTING.md#when-to-open-a-pull-request

# Notes for the reviewer
_Put any questions or notes for the reviewer here._

# Checklist
- [ ] Did you write tests?
- [ ] Did you write documentation?
- [ ] Did you change porter.yaml or a storage document record? Update the corresponding schema file.
- [ ] If this is your first pull request, please add your name to the bottom of our [Contributors][contributors] list. Thank you for making Porter better! 🙇‍♀️

# Reviewer Checklist
* Comment with /azp run test-porter-release if a magefile or build script was modified
* Comment with /azp run porter-integration if it's a non-trivial PR

[contributors]: https://getporter.org/src/CONTRIBUTORS.md

### CODE REVIEW

**Comment by carolynvs** [comment]
I tried out the preview in FireFox's responsive web design mode and everything looked great except for this one ipad view. The github icon is being turned into a blue button and looks odd. The other sizes don't do this.

Screenshot 2023-02-08 at 5 00 40 PM

**Comment by Arhell** [comment]
> I tried out the preview in FireFox's responsive web design mode and everything looked great except for this one ipad view. The github icon is being turned into a blue button and looks odd. The other sizes don't do this. If you know how to fix this in this PR, that would be great but otherwise I can make a separate issue.
> 
> Screenshot 2023-02-08 at 5 00 40 PM

Fix

**Comment by carolynvs** [comment]
Are you able to figure out why it's only in that one size that the github icon is displayed? All the other sizes in that firefox responsive design mode do not have the github icon as a button at all, and in fact I don't see the github icon at all on those sizes.

Can we have the github icon show up for the other sizes too? I'm not sure why it's being excluded for most sizes.

**Comment by Arhell** [comment]
> Are you able to figure out why it's only in that one size that the github icon is displayed? All the other sizes in that firefox responsive design mode do not have the github icon as a button at all, and in fact I don't see the github icon at all on those sizes.
> 
> Can we have the github icon show up for the other sizes too? I'm not sure why it's being excluded for most sizes.

removed the class, should now be displayed on a mobile device

**Review by carolynvs — APPROVED** [review]
It looks so much better, thanks!

**Pull request merged**
