### PR TITLE
change to 1.21.3

### PR DESCRIPTION
**Pull request by troy0820**
Because main is on 1.20.7 and the pipeline is using main's yaml template, we have to update this so the rest of the PRs can do the integration tests and not fail.

### CODE REVIEW

**Comment by troy0820** [comment]
These pipelines may fail

**Comment by schristoff** [comment]
is this dependent on #2999 
also happy 3000 🎉

**Comment by troy0820** [comment]
#2999 kinda fixes this but wanted to see if this was merged in first would the int tests pass because it needs the yaml@main to have the right go version.

**Comment by troy0820** [comment]
Also may keep this PR ready for review because it’s 3000 lol

**Comment by schristoff** [comment]
:( Goodbye 3k, you were cool

**Pull request closed without merging**
