### PR TITLE
docs: move links, add project clarification

### LINKED ISSUE #1031: Documentation issue with good first issues on CONTRIBUTING
## Bug with Documentation

On the [CONTRIBUTING](https://porter.sh/src/CONTRIBUTING.md) doc, the link to good first issues takes you to the project board which has a single first issue. This may not be as helpful to new people to the project. 

Additionally, 
- [x] A great first issue "What is Porter" is missing from the project board. (ETA, we've added this issue to the project board)
- [ ] Maybe remove the link to the project board from the "Find an Issue" section, or modify where it clicks to, or add a "See good examples below" example. 

Collaborating on bug report with @jacciboggs, @cjthune, and @alynch-code

## Expected behavior
1. Remove the links to good first issue and help wanted from the first paragraph under "find an issue"
1. Link to them instead later underneath the bullet points that explain what they mean. For example, let's say "Go to our project board and filter the issues by good first issue (link) or help wanted (link) to see available issues".
1. Add a sentence after we mention the project board in the first paragraph that explains that our project board contains issues from all of the Porter repositories so that it's easier to find issues without looking in each repo, e.g. "We use an organization level project board so we can see all issues associated with the project at once"

### PR DESCRIPTION
**Pull request by nhcarrigan**
Signed-off-by: nhcarrigan <nhcarrigan@gmail.com>

# What does this change
_Give a summary of the change, and how it affects end-users. It's okay to copy/paste your commit messages._

_For example if it introduces a new command or modifies a commands output, give an example of you running the command and showing real output here._

- Moves the links for the `good first issue` and `help wanted` labels from the first paragraph to the bullet list below. 
- Adds a statement to the first paragraph that clarifies the global scope of the project board.

# What issue does it fix
Closes #1031 

_If there is not an existing issue, please make sure we have context on why this change is needed. See our Contributing Guide for [examples of when an existing issue isn't necessary][1]._

[1]: /CONTRIBUTING.md#when-to-open-a-pull-request

# Notes for the reviewer
_Put any questions or notes for the reviewer here._

# Checklist
- [X] Unit Tests
- [X] Documentation
- [X] Schema (porter.yaml)

If this is your first pull request, please add your name to the bottom of our [Contributors][contributors] list. Thank you for making Porter better! 🙇‍♀️

[contributors]: /CONTRIBUTORS.md

### CODE REVIEW

**Review by carolynvs — APPROVED** [review]
Thanks for making our contributing guide better! 💖

**Comment by carolynvs** [comment]
There was a slight hiccup with the build not reporting its status properly back to GitHub. The build passed though, so I'm merging even though it doesn't show up as completed here in the pull request.

**Comment by carolynvs** [comment]
@nhcarrigan Since we aren't using a github app to help us list all of our contributors, would you like to submit a PR to add your name to https://github.com/getporter/porter/blob/main/CONTRIBUTORS.md? Or if you are okay with it, I can add you myself.

**Comment by nhcarrigan** [comment]
Sure I can submit the PR momentarily 🙂

**Pull request merged**
