### PR TITLE
fix(examples/service-fabric-cli): fix Dockerfile build

### PR DESCRIPTION
**Pull request by vdice**
# What does this change
* Fix for a build failure for this example bundle as seen in (unrelated PR) https://github.com/getporter/porter/pull/1387
* Once the above was fixed, we hit an issue wherein we hadn't pinned the json validator cli (`ajv-cli`) to a version and were hence pulling latest.  There are breaking changes in the latest (perhaps we can look into this at a later date); for now, we pin to a known quantity (3.3.0)

# What issue does it fix
N/A

# Notes for the reviewer
N/A

# Checklist
- [ ] Unit Tests
- [ ] Documentation
- [ ] Schema (porter.yaml)

### CODE REVIEW

**Comment by vdice** [comment]
Appear to be hitting https://github.com/getporter/porter/issues/1389 (or a variant thereof)

**Comment by carolynvs** [comment]
Docker crashed on the windows agent and didn't restart. For now I have deleted the unhealthy agent so that Azure will provision a new one. Later I'll look into preventing that from happening in the future.

**Comment by carolynvs** [comment]
Docker is configured to check for new versions I think. So it's hanging and preventing the docker service from starting. I'm going to see about fixing the agent image to not check for updates since it's so disruptive.

**Review by carolynvs — APPROVED** [review]
Pinning FTW! 🧷

**Pull request merged**
