### PR TITLE
Blog about the helm3 v0.1.14 mixin release

### PR DESCRIPTION
**Pull request by carolynvs**
Explain the latest release and why Porter moved to it immediately.

https://deploy-preview-1777--porter.netlify.app/blog/helm3-updates/

### CODE REVIEW

**Review by vdice — COMMENTED** [review]
Not sure if this is still being worked on.  So far, looks/reads great!

**Comment by MChorfa** [comment]
I have `--timeout` and  `--debug` ready to be merged and released in a new version.  If it is not too late we can reference the newest yet-to-be-released version. Otherwise, very nice blog post, super clear and informative ❤️

**Review by MChorfa — APPROVED** [review]

**Comment by carolynvs** [comment]
@MChorfa I'm happy to wait until you give me the 👍 to publish, with any new changes in the latest release.

**Comment by MChorfa** [comment]
Done : https://github.com/MChorfa/porter-helm3/releases/tag/v0.1.15

**Comment by carolynvs** [comment]
@MChorfa I have updated the post with notes from the v0.1.15 release. Please take a look.

**Comment by MChorfa** [comment]
LGTM!

**Pull request merged**
