### PR TITLE
Remove workflow_dispatch from test-porter-release action

### PR DESCRIPTION
**Pull request by kichristensen**
# What does this change
Parameters cannot be used when triggered by anything other than workflow_dispatch. As this action is also triggered on PRs targeting the main branch, it cannot use parameters. An example of a failing action can be found here https://github.com/getporter/porter/actions/runs/8909019136.
Instead the parameters are no longer dynamic and the default values have been hardcoded.

**UPDATE**:
As the content of this workflow is already covered by the `porter/porter-canary` workflow, `test-porter-release` is deleted instead.

# Checklist
- [ ] Did you write tests?
- [ ] Did you write documentation?
- [ ] Did you change porter.yaml or a storage document record? Update the corresponding schema file.
- [ ] If this is your first pull request, please add your name to the bottom of our [Contributors][contributors] list. Thank you for making Porter better! 🙇‍♀️

[contributors]: https://porter.sh/src/CONTRIBUTORS.md

### CODE REVIEW

**Comment by schristoff** [comment]
Now this is showing "test-porter-release" job on PRs, and I think we only want it on nightly or when there is a merge into main :/

**Comment by kichristensen** [comment]
@schristoff Good point, actually we might not want it at all, as the flow is also "tested" when producing the canary build on merge to main. That could be an argument for deleting the workflow all together. What to you think?

**Comment by schristoff** [comment]
I'm cool with deleting it :)

**Comment by kichristensen** [comment]
@schristoff it is deleted instead

**Review by schristoff — APPROVED** [review]

**Pull request merged**
