### PR TITLE
(bug): Flake in TestTelemetrySetup

### PR DESCRIPTION
**Pull request by schristoff**
Seeing what is flaky and what isn't rn

### CODE REVIEW

**Comment by schristoff** [comment]
huge shoutout to @gulducat to helping debug this

**Review by troy0820 — APPROVED** [review]
Lgtm

**Comment by troy0820** [comment]
Squash when you pass through the gates.

**Comment by schristoff** [comment]
Shh, don't let the integ test hear us assume I will make it through :p

**Pull request merged**
