### PR TITLE
fixed version based typos

### LINKED ISSUE #2769: In QucikStart: Bundles should v0.1.0 be changed to v0.2.0?
**What is your question?**
In QucikStart: Bundles we are installing v0.2.0 but below its written " *installing v0.1.0* "

Screenshot 2023-05-29 at 5 27 19 PM
 
The name of the bundle i installed is named *examples/porter-hello* but in docs its written *HELLO*

what i got -
Screenshot 2023-05-29 at 5 25 54 PM
What is in the documentation -
Screenshot 2023-05-29 at 5 38 49 PM

**What have you tried already?**

**Where have you looked already to figure this out?**

**Was the existing documentation unclear or had gaps?**

### PR DESCRIPTION
**Pull request by sbdtu5498**
# What does this change
Fixes few version-related typos

# What issue does it fix
Closes #2769 

# Checklist
- [ ] Did you write tests?
- [ ] Did you write documentation?
- [ ] Did you change porter.yaml or a storage document record? Update the corresponding schema file.
- [ ] If this is your first pull request, please add your name to the bottom of our [Contributors][contributors] list. Thank you for making Porter better! 🙇‍♀️

# Reviewer Checklist
* Comment with /azp run test-porter-release if a magefile or build script was modified
* Comment with /azp run porter-integration if it's a non-trivial PR

[contributors]: https://getporter.org/src/CONTRIBUTORS.md

### CODE REVIEW

**Review by schristoff — APPROVED** [review]
Heya, thank you so much! Please update your branch and we can merge it in :)

**Comment by sbdtu5498** [comment]
> Heya, thank you so much! Please update your branch and we can merge it in :)

Did it.

**Comment by sbdtu5498** [comment]
cc: @schristoff @bdegeeter @sgettys this one looks good to be merged. Kindly approve.

**Review by schristoff — APPROVED** [review]

**Pull request merged**
