### PR TITLE
Accessibility add alt to home page images

### PR DESCRIPTION
**Pull request by Arhell**
# What issue does it fix
Closes https://github.com/getporter/porter/issues/2607

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
@carolynvs take a look please

**Review by carolynvs — CHANGES_REQUESTED** [review]
The purpose of the alt text is to provide sufficient detail about the image for low-vision and blind users so that they understand whatever relevant information the image was providing to sighted users. The alt text in this PR doesn't do that, and instead is acting more like a header text for the image.

If you would like to try again, here's a page that gives examples of how to to write alt text:

https://accessibility.huit.harvard.edu/describe-content-images

**Comment by Arhell** [comment]
I've updated, if you need to add or remove anything let me know

**Comment by carolynvs** [comment]
@Arhell Here's an example of what good alt text would look like for one of the images on Porter's homepage



```
The porter.yaml file, a parameter named aks-cluster-name is circled and an arrow is pointing to where the parameter is used in a template further below, where in the installation action of the bundle, the parameter is passed to the azure ARM mixin.
```

For the icons, a better alt text for "lock image" would be "padlock" as it's more specific to what is displayed (there are lots of types of locks but padlock helps describe what is shown), and the word "image" is removed since alt text only describes images.

Does that help clear up how to add alt text if you are still interested?

**Comment by carolynvs** [comment]
@Arhell Setting the alt text to empty doesn't help someone using a screen reader, so I'm really confused about what you are hoping to accomplish with this PR. I'm going to close this for now since I don't think this is very productive and would best be worked out in an issue first to get agreement on the motivation for the change and how it should look.

**Pull request closed without merging**
