### PR TITLE
Move examples into example-bundles repository

### PR DESCRIPTION
**Pull request by carolynvs**
# What does this change
Remove the example bundles in /examples/ and point to the relocated example bundles in https://github.com/getporter/examples

# What issue does it fix
N/A

# Notes for the reviewer

It's not as awful to review as it looks, it's mostly deletes. 💥

# Checklist
- [ ] Did you write tests?
- [ ] Did you write documentation?
- [ ] Did you change porter.yaml or a storage document record? Update the corresponding schema file.
- [ ] If this is your first pull request, please add your name to the bottom of our [Contributors][contributors] list. Thank you for making Porter better! 🙇‍♀️

# Reviewer Checklist
* Comment with /azp run test-porter-release if a magefile or build script was modified
* Comment with /azp run porter-integration if it's a non-trivial PR

[contributors]: https://porter.sh/src/CONTRIBUTORS.md

### CODE REVIEW

**Review by vdice — APPROVED** [review]

**Comment by carolynvs** [comment]
Thanks for the review on this chonkin' PR! 💖

**Pull request merged**
