### PR TITLE
feat: Automates changelog.md when a release is published

### PR DESCRIPTION
**Pull request by itsaviral2609**
# What does this change

Having a well documented changelog is crucial for bug finding and enabling our users to be informed on our changes before they update. But keeping a changelog up to date is hard with everything else going on, and so enabling us (and our community) to be able to easily update the changelog with each change would be great.

- [x] Successfully created workflow in 'itsaviral2609-changelog' branch to test on forked repo

Screenshot from 2023-07-17 22-15-43

- [x] Creating a Release which will trigger the workflow on your branch

Screenshot from 2023-07-17 22-17-11

- [x]  Testing the changelog workflow which get triggered after a release is published

Screenshot from 2023-07-17 22-25-08

- [x]  A CHANGELOG.md is generated when a release is published in your forked repo
  
Screenshot from 2023-07-17 22-26-11

# What issue does it fix
Closes # 2797

# Notes for the reviewer

I was learning github actions and tried to apply on this issue. There might be errors for master branch scenario but worked perfectly when I tried it on my local branch. Changes suggested by maintainers/community welcomed to get this feature merged

# Checklist
- [ ] Did you write tests?
- [ ] Did you write documentation?
- [x] Successfully created workflow on local branch
- [ ] Did you change porter.yaml or a storage document record? Update the corresponding schema file.
- [ ] If this is your first pull request, please add your name to the bottom of our [Contributors][contributors] list. Thank you for making Porter better! 🙇‍♀️

# Reviewer Checklist
* Comment with /azp run test-porter-release if a magefile or build script was modified
* Comment with /azp run porter-integration if it's a non-trivial PR

[contributors]: https://getporter.org/src/CONTRIBUTORS.md

### CODE REVIEW

**Comment by itsaviral2609** [comment]
```yaml
name: Generate Changelog
on:
  release:
    types: [published]

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: aviral-changelog
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install conventional-changelog-cli
        run: npm install -g conventional-changelog-cli

      - name: Generate changelog
        run: conventional-changelog -p angular -i CHANGELOG.md -s -r 0

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add CHANGELOG.md
          git commit -m "Update Changelog" || echo "No changes to commit"
          git push origin aviral-changelog  
```

workflow for my local branch which worked successfully!

**Comment by troy0820** [comment]
Please run `go run mage.go SetupDCO` to fulfill the requirements for submission.

**Comment by troy0820** [comment]
I left comments on the other PR which includes this change.  If we want to close this @itsaviral2609 we can so we don't have two PRs with the same thing.

**Comment by itsaviral2609** [comment]
This PR is being under review on issue  #2833

**Pull request closed without merging**
