### PR TITLE
Reduce heading whitespace on blog posts

### PR DESCRIPTION
**Pull request by carolynvs**
# What does this change
The blog posts have too much whitespace right now before H2 tags, which splits up the page oddly. This removes the extra space, just for blog posts.

# What issue does it fix
NA

# Notes for the reviewer
I could reduce the space even further because there is another padding statement that is adding padding to h2. That would impact ALL h2 tags on both blog posts and doc pages, not just the ones on the blog. What do you think?

# Checklist
- [ ] Did you write tests?
- [ ] Did you write documentation?
- [ ] Did you change porter.yaml or a storage document record? Update the corresponding schema file.
- [ ] If this is your first pull request, please add your name to the bottom of our [Contributors][contributors] list. Thank you for making Porter better! 🙇‍♀️

# Reviewer Checklist
* Comment with /azp run test-porter-release if a magefile or build script was modified
* Comment with /azp run porter-integration if it's a non-trivial PR

[contributors]: https://porter.sh/src/CONTRIBUTORS.md

### CODE REVIEW

**Comment by carolynvs** [comment]
Example of the extra space between headings
screenshot


<details><summary>Browser metadata</summary>





```
Path:      /blog/v1-alpha3/
Browser:   Firefox 95.0 on Mac OS 10.15
Viewport:  2109 x 1179 @1x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1871--porter.netlify.app%2Fblog%2Fv1-alpha3%2F&os=OS%20X&os_version=Catalina&browser=Firefox&browser_version=95.0&resolution=2109x1179&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-1871--porter.netlify.app/blog/v1-alpha3/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=61f0847231b3be00079d754a&commentID=61f08541463dc10af5cefb9a&resolution=resolved)

**Review by VinozzZ — APPROVED** [review]
LGTM
The current heading space on the doc pages doesn't look too big for me. Have we thought about removing the added paddings for the global `h2` and let each component has its own header padding defined?

**Comment by carolynvs** [comment]
@VinozzZ I am not sure that I am following what you are suggesting. If you want to open a PR and demonstrate what you are suggesting that would be great.

**Review by joshuabezaleel — APPROVED** [review]
LGTM, thank you for the fix Carolyn!

**Pull request merged**
