### PR TITLE
fix(docker.go): don't exclude Dockerfile and .dockerignore from build context

### PR DESCRIPTION
**Pull request by vdice**
# What does this change
* Uses the docker cli [TrimBuildFilesFromExcludes](https://github.com/docker/cli/blob/master/cli/command/image/build/dockerignore.go#L28-L39) helper to be sure _not_ to exclude the Dockerfile and .dockerignore files when building the installer image.  Though, as noted in the helper docs, both will be removed from the final context (if both exist in the user-supplied .dockerignore).

# What issue does it fix
@squillace was hitting the following when `Dockerfile` was added to a bundle's `.dockerignore` file:

```
$ porter build
...
Starting Invocation Image Build =======>
Error: unable to build CNAB invocation image: Error response from daemon: Cannot locate specified Dockerfile: Dockerfile
```

# Notes for the reviewer

# Checklist
- [x] ~Unit~ Integration Tests
- [ ] Documentation
- [ ] Schema (porter.yaml)

If this is your first pull request, please add your name to the bottom of our [Contributors][contributors] list. Thank you for making Porter better! 🙇‍♀️

[contributors]: /CONTRIBUTORS.md

### CODE REVIEW

**Comment by carolynvs** [comment]
Are these files (Dockerfile, .dockerignore) excluded by default? Or were they added by the user? I think I'm missing some context into the troubleshooting and what the root cause was here.

If the files were called Dockerfile.foo and Dockerfile.foo.dockerignore would they have been excluded?

**Comment by squillace** [comment]
it's very common -- and a practice I use -- to reject all files in the .dockerignore by default and then add IN the app artifacts you really need. BUT... it's easy to NOT know what files the container MUST have added in, so in this case, if you have a .dockerignore file but have forgotten to enable Dockerfile you get this error, but you have no idea why it happened. 

It's a basic ux thing that an expert like you would not do (because you'd always know that docker needs the Dockerfile inside the context to build it). :-) Does that help?

**Comment by vdice** [comment]
This fix just ensures that Porter can build the installer/invocation image even if the .dockerignore file in the bundle directory has an entry matching the name of the Dockerfile that Porter uses/needs to build from.  So, the .dockerignore might look like:

```
stuff-i-don't-want-in-the-installer-image
Dockerfile # which I also don't want in the installer image
.dockerignore # ditto
```

And, indeed, all of the files above _won't_ end up in the final image, but with this fix we ensure that `Dockerfile` and `.dockerignore` are accessible to the daemon performing the build.

> If the files were called Dockerfile.foo and Dockerfile.foo.dockerignore would they have been excluded?

Yes.  The helper matches ".dockerignore" [specifically](https://github.com/docker/cli/blob/master/cli/command/image/build/dockerignore.go#L32) and the Dockerfile string config'd on Porter's [build options](https://github.com/deislabs/porter/blob/main/pkg/build/provider/docker.go#L43) (currently "Dockerfile") -- all other files/filenames present in the user-supplied .dockerignore _will_ be excluded in all contexts.

**Comment by carolynvs** [comment]
Thanks for clarifying. So when we implement https://github.com/getporter/porter/issues/1162, we will need to update this fix if we rename Dockerfile/.dockerfileignore. Gotcha. 👍

**Review by carolynvs — APPROVED** [review]
LGTM

**Pull request merged**
