### PR TITLE
Bug #2785

### PR DESCRIPTION
**Pull request by alekseybb197**
# What does this change
Fix for Bug https://github.com/getporter/porter/issues/2785 porter param list doesn't display params

Wrong line "cr, ok := v.(DisplayCredentialSet)" was changed to "cr, ok := v.(DisplayParameterSet)"

# What issue does it fix

Closes # bug #2785 

# Notes for the reviewer
_Put any questions or notes for the reviewer here._

# Checklist
- [ ] Did you write tests?
- [ ] Did you write documentation?
- [ ] Did you change porter.yaml or a storage document record? Update the corresponding schema file.
- [ ] If this is your first pull request, please add your name to the bottom of our [Contributors][contributors] list. Thank you for making Porter better! 🙇‍♀️

# Reviewer Checklist
* Comment with /azp run test-porter-release if a magefile or build script was modified
* Comment with /azp run porter-integration if it's a non-trivial PR

[contributors]: https://getporter.org/src/CONTRIBUTORS.md

### CODE REVIEW

**Review by troy0820 — CHANGES_REQUESTED** [review]
If you re-did your fork, it is still showing signs of commits that seem to be in already.  I'll defer to @schristoff on this one but it doesn't look like this resolve the issue with the PR you submitted.

**Comment by schristoff** [comment]
I think we should be able to just squash this and it'll be okay. 🙏🏻

**Comment by alekseybb197** [comment]
Guys, I'm on vacation in Israel. I have a lot of free time)

**Pull request closed without merging**
