### PR TITLE
🎨 Align date to left and put under title in article/blog page

### LINKED ISSUE #1302: blog design: dangling date in single blog post view
I'm not sure if it's intentional or not but it seems like the date is dangling off to the side on the single blog post view. 

Example page: https://porter.sh/blog/docker-mixin-blog-post/

If it's intentional just close this issue. 

---
Notes:
* Goal: Make the date look prettier for blog post pages. Either directly under the title or what I was trying to do was make it on the same level as the title but on the right hand side.
* The changes need to be made to our Hugo theme Sass and/or layouts in https://github.com/getporter/porter/tree/main/docs/themes/porter. Blog posts use the layouts/blog/single.html page and the sass is mostly in static/sass/helm-blog.scss
* You can preview your changes by following the instructions in the [Contributing Guide](https://porter.sh/src/CONTRIBUTING.md#preview-documentation).

### PR DESCRIPTION
**Pull request by dev-drprasad**
# What does this change
Align date to left and put under title in article/blog page

Before PR:
Screenshot 2020-10-06 at 3 37 58 PM

After PR:
Screenshot 2020-10-06 at 3 38 08 PM

# What issue does it fix
Closes #1302 

[1]: /CONTRIBUTING.md#when-to-open-a-pull-request

# Notes for the reviewer
N/A

# Checklist
- [x] Unit Tests - N/A
- [x] Documentation - N/A
- [x] Schema (porter.yaml) - N/A

[contributors]: /CONTRIBUTORS.md

### CODE REVIEW

**Review by carolynvs — APPROVED** [review]
Looks much better, thanks!

**Comment by carolynvs** [comment]
Oops, the [DCO check](https://github.com/getporter/porter/blob/main/CONTRIBUTING.md#signing-your-commits) is failing. You can fix it by running `git commit --amend -s` then force pushing back up to your branch.

**Review by iennae — APPROVED** [review]
Awesome! Thanks for fixing. Don't forget to do the DCO process :D

**Comment by dev-drprasad** [comment]
All checks have passed

**Pull request merged**
