### PR TITLE
Change v1 branch to release/v1

### PR DESCRIPTION
**Pull request by carolynvs**
# What does this change
This will help us target the release process based on the branch name (i.e. release/* vs listing each release name). It also avoids a conflict with how go mods work, we should not have selected a branch name that resembles semver.

Now in addition to v1.0.0-*, we will publish v1-canary and v1-latest.

After this merges I will rename v1 -> release/v1 and merge this change into it. I am making the change to both branches so that we aren't running with dramatically different build scripts on each branch.

# What issue does it fix
None

# Notes for the reviewer
Since I changed how the permalink is calculated, I had to move a bunch more logic from make into mage.

# Checklist
- [ ] Unit Tests
- [x] Documentation
- [ ] Schema (porter.yaml)

### CODE REVIEW

**Comment by carolynvs** [comment]
@vdice This is ready for review! I have run a test release and verified the following:
* release uploaded to github (I'll remove it when we merge this PR) https://github.com/getporter/porter/releases/tag/change-v1-branch-name-canary
* images published to docker hub https://hub.docker.com/layers/getporterci/porter/change-v1-branch-name-canary/images/sha256-a66d1afa92e350da26ac4310ed56df0e13bf10c07f3f43297455f0d0fcdfc7c2?context=explore
* mixin feed published to getporter/packages https://github.com/getporter/packages/commit/f9f5948308a5611c5a7fdd999ecc0321fcbc0ac3 (reverted already)

**Review by vdice — APPROVED** [review]
`LoadMetadata()` brings a lot of nice cleanup!  LGTM

**Comment by carolynvs** [comment]
just close your eyes tight, and merge 😝

**Pull request merged**
