### PR TITLE
Adding pagination for installation list result using skip and limit option

### LINKED ISSUE #2051: Add paging options to porter list and other commands that list installation data
We have support in the underlying plugin protocol to page data when listing, but we still don't expose flags for that in the CLI. At some point we should add those flags in so that people with a significant number of installations, or long lived often updated installations don't run into performance problems.

Adding this post 1.0 won't be a breaking change because the plugins already support it.

### PR DESCRIPTION
**Pull request by joshuabezaleel**
# What does this change
User that use the Porter CLI can use `--skip` and `--limit` flag for paginating their list output.

# What issue does it fix
Closes #2051 

# Notes for the reviewer

# Checklist
- [x] Did you write tests?
- [ ] Did you write documentation?
- [ ] Did you change porter.yaml or a storage document record? Update the corresponding schema file.
- [ ] If this is your first pull request, please add your name to the bottom of our [Contributors][contributors] list. Thank you for making Porter better! 🙇‍♀️

# Reviewer Checklist
* Comment with /azp run test-porter-release if a magefile or build script was modified
* Comment with /azp run porter-integration if it's a non-trivial PR

[contributors]: https://porter.sh/src/CONTRIBUTORS.md

### CODE REVIEW

**Comment by joshuabezaleel** [comment]
I am sorry I think I made a new branch from the wrong branch/commit, I'll close this one and made another one 😔

**Comment by joshuabezaleel** [comment]
I think it's because the target branch is `main`, my bad ..

**Comment by carolynvs** [comment]
Just a heads up that if the problem was that when you made the PR you accidentally picked "main" instead of "release/v1", you can change that by clicking the edit button by the title of your PR and then you can change the target branch.

**Comment by joshuabezaleel** [comment]
@carolynvs My bad, yesterday I thought the edit button was only for the PR title that's why what I did was made [another PR](https://github.com/getporter/porter/pull/2137) for this branch. So sorry for the inconvenience ..

**Comment by carolynvs** [comment]
It doesn't inconvenience me at all! I just wanted you to know so that you can fix it next time. 👍

**Comment by joshuabezaleel** [comment]
@carolynvs will always be grateful for you and others being really eaccommodating, Carolyn. thank you so much! Looking forward to the review 😄

**Pull request closed without merging**
