### PR TITLE
changes for mobile view

### PR DESCRIPTION
**Pull request by reveurguy**
Signed-off-by: reveurguy <reveur.guy99@gmail.com>

# What does this change
Made changes to the website look for mobile view. Corrected the UI to look better.

_For example if it introduces a new command or modifies a commands output, give an example of you running the command and showing real output here._

# What issue does it fix
Closes # _(issue)_

_If there is not an existing issue, please make sure we have context on why this change is needed. See our Contributing Guide for [examples of when an existing issue isn't necessary][1]._

[1]: https://porter.sh/src/CONTRIBUTING.md#when-to-open-a-pull-request

# Notes for the reviewer
_Put any questions or notes for the reviewer here._

# Checklist
- [ ] Did you write tests?
- [ ] Did you write documentation?
- [ ] Did you change porter.yaml or a storage document record? Update the corresponding schema file.
- [ ] If this is your first pull request, please add your name to the bottom of our [Contributors][contributors] list. Thank you for making Porter better! 🙇‍♀️

# Reviewer Checklist
* Comment with /azp run test-porter-release if a magefile or build script was modified
* Comment with /azp run porter-integration if it's a non-trivial PR

[contributors]: https://porter.sh/src/CONTRIBUTORS.md

### CODE REVIEW

**Comment by VinozzZ** [comment]
Thank you for improving our mobile site experience! I tested it out on my IPhone 11. It looks great!
One thing I wanted to ask if you can help us to make each text link to appear in one line instead of two in the below screenshot 
image

**Comment by reveurguy** [comment]
Actually I haven't made changes to that section, in web view also , so i was planning to make the changes in both views in one go.

**Comment by reveurguy** [comment]
Actually nevermind, made the changes. Was about to shutdown the laptop but made the changes. 😀

**Comment by reveurguy** [comment]
Any update on this PR? Is there any feedback or change required?

**Pull request merged**
