### PR TITLE
Update helm3 mixin doc

### PR DESCRIPTION
**Pull request by MChorfa**
Document how to specify multiple values.

# What issue does it fix
Closes https://github.com/MChorfa/porter-helm3/issues/24

# Checklist
- [ ] Unit Tests
- [x] Documentation
- [ ] Schema (porter.yaml)

### CODE REVIEW

**Review by carolynvs — APPROVED** [review]
lgtm

**Comment by carolynvs** [comment]
@MChorfa can you add your signature to the commit message so that the DCO check to pass?

https://porter.sh/contribute/guide/#signing-your-commits

**Comment by MChorfa** [comment]
DCO  is refusing to go through no matter how I sign

**Comment by carolynvs** [comment]
The problem is on this commit https://github.com/getporter/porter/pull/1749/commits/2f46fb9bead4c58cd45e137bca0ea7941e91ba05. It is missing the "signed-off by" line at the end of the message.

**Comment by carolynvs** [comment]
If you are having trouble with git, just comment here that's it's okay for me to squash your 3 commits and use your signoff on the other commits as signoff for the entire PR.

**Comment by MChorfa** [comment]
Yes, please, signing off the commits . For the next time, I will have my machine set up correctly. sorry :(

**Comment by carolynvs** [comment]
No worries, I mess up the DCO pretty regularly and it takes a bit of effort with git to fix it. Thank you for the updated docs! 💖

**Pull request merged**
