### PR TITLE
Listed the Kubernetes Plugin on Plugin Page

### LINKED ISSUE #1591: List kubernetes plugin on the plugins page
We should document the Kubernetes plugin on our [plugins](https://porter.sh/plugins/) page.

* Here is where we need a page added: https://github.com/getporter/porter/tree/main/docs/content/plugins
* The page should contain a subset of the information on the [kubernetes plugin readme](https://github.com/getporter/kubernetes-plugins/blob/main/README.md), and show the same type of information as with the [azure plugin](https://porter.sh/plugins/azure).

### PR DESCRIPTION
**Pull request by DARK-art108**
# What does this change
Added Doc for Integration of Porter with Kubernetes, using Kubernetes Plugin on Plugin Page.

# What issue does it fix
Closes #1591 

[1]: /CONTRIBUTING.md#when-to-open-a-pull-request

# Notes for the reviewer
_Put any questions or notes for the reviewer here._

# Checklist
- [ ] Unit Tests
- [x] Documentation
- [ ] Schema (porter.yaml)

If this is your first pull request, please add your name to the bottom of our [Contributors][contributors] list. Thank you for making Porter better! 🙇‍♀️

[contributors]: /CONTRIBUTORS.md

### CODE REVIEW

**Review by carolynvs — APPROVED** [review]
Perfect, thank you! 💖 Since this is your first pull request, would you like to add your name to our [CONTRIBUTORS.md](https://github.com/getporter/porter/blob/main/CONTRIBUTORS.md) file as well?

**Comment by DARK-art108** [comment]
Yes @carolynvs

**Comment by carolynvs** [comment]
Great! I'll leave this PR open until you add another commit with your name on the contributors page. 👍

**Comment by DARK-art108** [comment]
@carolynvs I have added myself to the list :)

**Comment by DARK-art108** [comment]
I think PR looks good to merge! Any Changes needed? @carolynvs

**Review by carolynvs — APPROVED** [review]
LGTM!

**Pull request merged**
